### ISSUE TITLE
build:web "missing script"

### ISSUE THREAD

**Issue by raould** [Schmavery/reprocessing#65]
hi, i am excited about this project, it is getting me to try out Reason. :-) but, clueless newb here...

- ubuntu 16.04
- mkdir Test && cd Test
- npm init
- npm install --save schmavery/reprocessing (er, is it bad to use that flag? but should i not maintain a dependency on reprocessing somehow?)
- i created ./src/Test.re
- npm run build:web (like the README.md told me to)
- npm ERR! missing script: build:web

when i look at your https://github.com/Schmavery/reprocessing/blob/master/package.json I do not see build:web in there as a script, if that is relevant? although "npm run build" doesn't work for me either. (what is the diff between "build" vs. "build:web" anyhoo?)

Linux 4.4.0-112-generic
argv "/usr/bin/node" "/usr/bin/npm" "run" "build:web"
node v9.5.0
npm  v5.6.0

**Comment by bsansouci** [comment]
Hey! What’s the error when running `npm run build`?
That’s definitely the command to run to build for web. I’ll update the readme.

**Comment by raould** [comment]
Basically the same error. There's no node_modules/.bin, should I have gotten one? 


```
$ npm run build
npm ERR! missing script: build
```
[2018-02-08T06_40_26_246Z-debug.log](https://github.com/Schmavery/reprocessing/files/1705952/2018-02-08T06_40_26_246Z-debug.log)

**Comment by Schmavery** [comment]
Ah, I think I see what the problem is here. Sorry, the instructions seem to assume a little familiarity with npm/package.json.

If you clone the reprocessing repo and then run `npm install`, it will install all dependencies after which you can `npm run build` as mentioned to build everything (including some examples projects).

**However**, it looks like you're trying to create a new project that uses reprocessing as a dependency.  What you're doing is fine (along with the --save 😄), but that build script is defined in *reprocessing's*  package.json, not in *your project's* package.json (which has reprocessing as a dependency).

The easiest way for you to get a start on a project like this would be to clone this repo: https://github.com/bsansouci/reprocessing-example and then run `npm install` inside the clone.  Hope that helps!

**Comment by raould** [comment]
thanks will do
